# Requirements for the project's conda virtual environment
name: xml-api
channels:
  - conda-forge
dependencies:
  - python=3.11.9
  - black=24.4.2
  - mypy=1.10.1
  - pytest=8.2.2
  - pytest-django=4.8.0
  - django=5.0.7
  - djangorestframework=3.15.2
  - gunicorn=22.0.0

####### USAGE #########
# Install env with:
# conda env create --prefix ./.env -f environment.yml
# 
# Shortent env prompt:
# conda config --set env_prompt '({name})'
# 
# Activate env with:
# conda activate ./.env
# 
# Update env with:
# conda env update --prefix ./.env --file environment.yml --prune
# 
# Remove env with:
# conda deactivate && conda env remove --prefix ./.env
